#version: '3.8'
services:
  inference-node-1:
    build: ./group22_inference_service
    container_name: inference-node-1
    ports:
    - 8011:8000
    environment:
    - NODE_ID=node-1
    - N_THREADS=2
    volumes:
    - ./models:/models
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
  inference-node-2:
    build: ./group22_inference_service
    container_name: inference-node-2
    ports:
    - 8012:8000
    environment:
    - NODE_ID=node-2
    - N_THREADS=2
    volumes:
    - ./models:/models
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
  inference-node-3:
    build: ./group22_inference_service
    container_name: inference-node-3
    ports:
    - 8013:8000
    environment:
    - NODE_ID=node-3
    - N_THREADS=2
    volumes:
    - ./models:/models
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1536M
  load_balancer:
    build: ./group22_load_balancer
    container_name: load_balancer
    ports:
    - 8080:8080
    environment:
    - NODES=inference-node-1,inference-node-2,inference-node-3
    - ROUTING_STRATEGY=hardware-aware
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
    - inference-node-1
    - inference-node-2
    - inference-node-3
